# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [amd64, arm64]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'
          go-arch: ${{ matrix.arch }}
      - name: gomod1
        run: go mod init myclash
      - name: gomod2
        run: go mod tidy
      - name: Build
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: go build -buildmode=c-shared -o ./output/fulltclash-${{ matrix.os }}-${{ matrix.arch }}.so ./libs/fulltclash.go
      - name: Build
        if: ${{ matrix.os == 'windows-latest' }}
        run: go build -buildmode=c-shared -o ./output/fulltclash-${{ matrix.os }}-${{ matrix.arch }}.dll ./libs/fulltclash.go
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: fulltclash-${{ matrix.os }}-${{ matrix.arch }}
          if: ${{ matrix.os == 'ubuntu-latest' }}
          path: ./output/*.so
          if-no-files-found: error
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: fulltclash-${{ matrix.os }}-${{ matrix.arch }}
          if: ${{ matrix.os == 'windows-latest' }}
          path: ./output/*.dll
          if-no-files-found: error
#       - name: Upload artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: fulltclash-${{ matrix.os }}-${{ matrix.arch }}
#           path: ./output/*
#           if-no-files-found: error
